# Generated by Django 6.0 on 2026-02-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_uni', models.CharField(max_length=150, unique=True)),
                ('courses_offered', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='JambAcceptedSubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('subject_combination', models.JSONField(default=list)),
                ('core_subjects', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Universities_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_universities', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfBirth', models.PositiveSmallIntegerField()),
                ('monthOfBirth', models.CharField(max_length=15)),
                ('dateOfBirth', models.PositiveSmallIntegerField()),
                ('Universities_name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
