# Generated by Django 6.0 on 2026-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('otherName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('yearOfBirth', models.PositiveSmallIntegerField()),
                ('monthOfBirth', models.CharField(max_length=10)),
                ('dateOfBirth', models.PositiveSmallIntegerField()),
                ('universityName', models.CharField(max_length=100)),
                ('deptName', models.CharField(max_length=100)),
                ('currentLevel', models.CharField(max_length=20)),
            ],
        ),
    ]
