# Generated by Django 6.0 on 2026-02-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='deptName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='monthOfBirth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='otherName',
            field=models.CharField(max_length=200),
        ),
    ]
