# Generated by Django 6.0 on 2026-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('file_data', models.BinaryField()),
                ('file_type', models.CharField(max_length=100)),
            ],
        ),
    ]
