# Generated by Django 6.0 on 2026-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0002_alter_signup_deptname_alter_signup_monthofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='currentLevel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='dateOfBirth',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='deptName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='monthOfBirth',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='otherName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='universityName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='userEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='yearOfBirth',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
