# Generated by Django 6.0 on 2026-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0002_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesForEachDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150)),
                ('uni_name', models.CharField(max_length=150)),
                ('first_semester_courses', models.JSONField(default=list)),
                ('second_semester_courses', models.JSONField(default=list)),
            ],
        ),
    ]
