# Generated by Django 6.0 on 2026-02-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0003_alter_signup_currentlevel_alter_signup_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='universities_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_universities', models.CharField(choices=[('Federal University of Ilorin', 'Federal University of Ilorin'), ('Federal University of Lagos', 'Federal University of Lagos')], max_length=150, unique=True)),
            ],
        ),
    ]
