# Generated by Django 6.0 on 2026-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0003_coursesforeachdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforeachdept',
            name='first_semester_courses',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='coursesforeachdept',
            name='second_semester_courses',
            field=models.JSONField(default=list, null=True),
        ),
    ]
