# Generated by Django 6.0 on 2026-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0004_alter_coursesforeachdept_first_semester_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesforeachdept',
            name='first_semester_courses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='coursesforeachdept',
            name='second_semester_courses',
            field=models.JSONField(default=list),
        ),
    ]
