# Generated by Django 6.0 on 2026-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0004_universities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities_name',
            name='name_of_universities',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
