# Generated by Django 6.0 on 2026-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0005_alter_universities_name_name_of_universities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_uni', models.CharField(max_length=150, unique=True)),
                ('courses_offered', models.JSONField(default=list)),
            ],
        ),
    ]
