# Generated by Django 6.0 on 2026-02-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0006_coursenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='JambAcceptedSubjectCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('subject_combination', models.JSONField(default=list)),
            ],
        ),
    ]
