# Generated by Django 6.0 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpbrainApi', '0007_jambacceptedsubjectcombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='jambacceptedsubjectcombination',
            name='core_subjects',
            field=models.JSONField(default=list),
        ),
    ]
